from app.modules.vision.medical.category_registry import (
    MedicalCategory,
    ImageModality,
    DiseaseGroup,
    CategoryMetadata,
    DiseaseClassMapping,
    CATEGORY_REGISTRY,
    DISEASE_MAPPINGS,
    get_real_medical_categories,
    get_hard_negative_categories,
    get_trainable_disease_groups,
)
from app.modules.vision.medical.v6_training_config import (
    V6SubStage,
    V6SubStageConfig,
    V6TrainingConfig,
    V6ReplayConfig,
    V6CompatibilityConfig,
    BackboneUnfreezePolicy,
    V6_BINARY_MEDICAL_CONFIG,
    V6_BINARY_MEDICAL_CLASSES,
    V6_POSITIVE_CLASSES,
    V6_OOD_CLASSES,
    apply_backbone_policy,
    build_checkpoint_meta,
)
from app.modules.vision.medical.v6_evaluation import (
    V6Evaluator,
    V6EvaluationResult,
    OODMetrics,
    CalibrationMetrics,
    PerClassMetrics,
    GradCAMSanity,
    CompatibilityReport,
    export_evaluation_report,
    export_compatibility_report,
)

__all__ = [
    # Phase 7 — category registry
    "MedicalCategory",
    "ImageModality",
    "DiseaseGroup",
    "CategoryMetadata",
    "DiseaseClassMapping",
    "CATEGORY_REGISTRY",
    "DISEASE_MAPPINGS",
    "get_real_medical_categories",
    "get_hard_negative_categories",
    "get_trainable_disease_groups",
    # Phase 10 — v6 training config
    "V6SubStage",
    "V6SubStageConfig",
    "V6TrainingConfig",
    "V6ReplayConfig",
    "V6CompatibilityConfig",
    "BackboneUnfreezePolicy",
    "V6_BINARY_MEDICAL_CONFIG",
    "V6_BINARY_MEDICAL_CLASSES",
    "V6_POSITIVE_CLASSES",
    "V6_OOD_CLASSES",
    "apply_backbone_policy",
    "build_checkpoint_meta",
    # Phase 10 — v6 evaluation
    "V6Evaluator",
    "V6EvaluationResult",
    "OODMetrics",
    "CalibrationMetrics",
    "PerClassMetrics",
    "GradCAMSanity",
    "CompatibilityReport",
    "export_evaluation_report",
    "export_compatibility_report",
]
